version: "3"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  cloudflare-ddns:
    container_name: pve-cloudflareDNS
    image: oznu/cloudflare-ddns
    restart: always
    environment:
      PUID: 0
      PGID: 0
      API_KEY: k3o0IqMQHFSHWqRGFcSXEkic8kXGyLgv59zKyMrs
      ZONE: cityplug.co.uk
      SUBDOMAIN: pve.cityplug.co.uk

  portainer:
    container_name: portainer_agent
    image: portainer/agent:2.11.1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /opt/portainer:/data
    ports:
      - 9001:9001